
IF OBJECT_ID('spQuotesConsolidation') IS NOT NULL
	DROP PROC [dbo].[spQuotesConsolidation]
GO

CREATE PROC [dbo].[spQuotesConsolidation]
AS
INSERT INTO dbo.Quote (
	[SystemTime]
	, [symbol]
	, [avgTotalVolume]
	, [calculationPrice]
	, [change]
	, [changePercent]
	, [close]
	, [closeTime]
	, [delayedPrice]
	, [delayedPriceTime]
	, [extendedChange]
	, [extendedChangePercent]
	, [extendedPrice]
	, [extendedPriceTime]
	, [high]
	, [iexAskPrice]
	, [iexAskSize]
	, [iexBidPrice]
	, [iexBidSize]
	, [iexLastUpdated]
	, [iexMarketPercent]
	, [iexRealtimePrice]
	, [iexRealtimeSize]
	, [iexVolume]
	, [latestPrice]
	, [latestSource]
	, latestTime
	, [latestUpdate]
	, [latestVolume]
	, [low]
	, [marketCap]
	, [open]
	, [openTime]
	, [peRatio]
	, [previousClose]
	, [week52High]
	, [week52Low]
	, [ytdChange]
)
SELECT 
	[SystemTime]
	, [symbol]
	, [avgTotalVolume]
	, [calculationPrice]
	, [change]
	, [changePercent]
	, [close]
	, [closeTime]
	, [delayedPrice]
	, [delayedPriceTime]
	, [extendedChange]
	, [extendedChangePercent]
	, [extendedPrice]
	, [extendedPriceTime]
	, [high]
	, [iexAskPrice]
	, [iexAskSize]
	, [iexBidPrice]
	, [iexBidSize]
	, [iexLastUpdated]
	, [iexMarketPercent]
	, [iexRealtimePrice]
	, [iexRealtimeSize]
	, [iexVolume]
	, [latestPrice]
	, [latestSource]
	, TRY_CAST([latestTime] AS TIME(0)) latestTime
	, [latestUpdate]
	, [latestVolume]
	, [low]
	, [marketCap]
	, [open]
	, [openTime]
	, [peRatio]
	, [previousClose]
	, [week52High]
	, [week52Low]
	, [ytdChange]
FROM dbo.Quote_stag

TRUNCATE TABLE dbo.Quote_stag
